#!/bin/sh
# vi: ft=sh
mkdir -p ~/.config/containers/systemd/
( cd ~/.config/containers/systemd && curl -sSLO https://raw.githubusercontent.com/chrismaster/pods/main/example/examplebuild.build && sed -i -e "s/examplebuild/$1/g" examplebuild.build && mv examplebuild.build $1.build )
cd ~
ln -s .config/containers/systemd/$1.build ~/$1
loginctl enable-linger $USER
