#!/bin/sh
# vi: ft=sh
test -e ~/.config/containers/systemd/$1.container && echo "Container $1.container already exists --> EXIT" && exit || echo "Create $1.container"
mydir=$(pwd)
mkdir -p ~/.config/containers/systemd/
( cd ~/.config/containers/systemd && curl -sSLO https://raw.githubusercontent.com/chrismaster/pods/main/example/examplecontainer.container && sed -i -e "s/examplecontainer/$1/g" examplecontainer.container && mv examplecontainer.container $1.container )
ln -s ~/.config/containers/systemd/$1.container $mydir/$1
loginctl enable-linger $USER
