#!/bin/sh
# vi: ft=sh
mkdir -p ~/.config/containers/systemd/
( cd ~/.config/containers/systemd && curl -sSLO https://raw.githubusercontent.com/chrismaster/pods/main/example/examplepod.pod && sed -i -e "s/examplepod/$1/g" examplepod.pod && mv examplepod.pod $1.pod )
cd ~
ln -s .config/containers/systemd/$1.pod ~/$1-pod
loginctl enable-linger $USER
