#!/bin/sh
# vi: ft=sh
# pList List running containers
getent passwd | grep bash | awk -F: '{print $1}' | grep -v ^root$ | sort | \
xargs -Iusername \
sudo machinectl -q shell username@ \
/bin/bash -c 'podman ps -a --noheading --no-trunc'
