#!/bin/sh
# vi: ft=sh
# cleanup all user containers
getent passwd | grep bash | awk -F: '{print $1}' | grep -v ^root$ | sort | \
xargs -Iusername \
sudo machinectl -q shell username@ \
/bin/bash -c 'podman image prune -f -a'
